let myResume={
    "basics": {
      "name": "MANIMEKALAI M",
      "email": "manimekalai.eee123@gmail.com",
      "phone": 9715319070,
      "degree": "DEEE",
      "location": {
        "address": "17B., KS Street",
        "postalCode": 636005,
        "city": "Salem",
        "state": "Tamilnadu",
        "country": "India"
      },
      
    },
    "work": [
      {
        "company": "First American India",
        "position": "Subject Matter Expert",
        "startDate": "2015-08-03",
        "endDate": "2022-12-31",
        "summary": "i am the subject matter expert handling various task and gaining lots of experience",
      },
    ],
    "education": [
      {
        "institution": "Thiagarajar Polytechnic College",
        "department": "Electrical and Electronics Engg",
        "studyType": "fulltime",
        "batch start year": 2008,
        "batch end year": 2011,
        "Percentage": 92,
    },
    ],
    "skills": [
      {
        "name": "javascript",
        "level": "beginner",
        
      }
    ],
    "languages": [
      {
        "language": "Tamil,English",
      }
    ],
    "interests": [
      {
        "name": "baking and craft works",
      }
    ]
  }
console.log(myResume);

